---
title: "eda.rmd"
author: "Ishita Khanna"
date: "`r Sys.Date()`"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
library(tidyverse)
library(shiny)
library(widyr)
library(ggraph)
library(tidygraph)
library(igraph)
library(tidytext)

user2025 <- read_csv("data/user2025.csv") #reading the data set

glimpse(user2025) #overview

head(user2025$keywords, 10)
```

```{r sessions_by_date, echo=FALSE}
renderPlot({
  user2025 %>%
    count(date) %>%
    ggplot(aes(x = date, y = n)) +
    geom_col(fill = "steelblue") +
    labs(title = "Sessions by Date", x = "Date", y = "Number of Sessions") +
    theme_minimal() #sessions per date
})
```

```{r top_keywords, echo=FALSE}
inputPanel(
  sliderInput("top_key", "Number of top keywords to display:", min = 5, max = 30, value = 10)
)

renderPlot({
  keyword_counts <- user2025 %>%
    separate_rows(keywords, sep = ",") %>%
    mutate(keywords = str_trim(keywords)) %>%
    mutate(keywords = str_squish(keywords)) %>% 
    count(keywords, sort = TRUE)
  
  keyword_counts %>%
    slice_max(n, n = input$top_key) %>%
    mutate(keyword_short = str_wrap(str_trunc(keywords, width = 40), width = 20)) %>%
    ggplot(aes(x = reorder(keyword_short, n), y = n)) +
    geom_col(fill = "darkorange") +
    coord_flip() +
    labs(title = "Top Keywords", x = "Keyword", y = "Count") +
    theme_minimal(base_size = 13)
})
```

- Seeing which keywords tend to show up together in the same sessions

```{r keyword_network, echo=FALSE}
#prepare the data
renderPlot({
keyword_pairs <- user2025 %>%
  mutate(id = row_number()) %>%
  separate_rows(keywords, sep = ",") %>%
  mutate(keywords = str_squish(str_trim(keywords))) %>%
  filter(keywords != "", !is.na(session)) %>%
  unite(session_key, session, id, remove = FALSE) %>%
  distinct(session_key, keywords) %>%
  pairwise_count(item = keywords, feature = session_key, sort = TRUE, upper = FALSE)

filtered_pairs <- keyword_pairs %>%
  filter(n >= 2) # only keeping pairs that had multiple occurrence 

keyword_graph <- as_tbl_graph(filtered_pairs) #creating graph structure

ggraph(keyword_graph, layout = "fr") +
  geom_edge_link(aes(width = n), 
                 edge_colour = "#4D4D4D", alpha = 1) +
  geom_node_point(color = "#001F54", fill = "#F39C12", size = 12, shape = 21, stroke = 0.5) +
  geom_node_text(aes(label = name), 
                 repel = TRUE, size = 4.5, color = "#001F54", fontface = "bold", hjust = -0.2, vjust = 0.5) +
  scale_edge_width(range = c(0.5, 3), guide = "legend") +
  theme_void(base_family = "Arial") +
  theme(
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5, color = "#001F54"),
    plot.subtitle = element_text(size = 12, hjust = 0.5, color = "#444444"),
    plot.caption = element_text(size = 9, hjust = 1, color = "gray40")
  ) +
  labs(
    title = "Keyword Co-occurrence Network by Session",
    subtitle = "Vivid connections between frequently co-mentioned terms",
    caption = "Source: useR! 2025 Conference Program"
  )
})
```




